version: '3.8'

services:
  vue-test-website:
    image: umutayb/vue-test-site:test
    restart: always
    ports:
      - "8080:8080"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge
