version: '3.8'

services:
  vue-test-website:
    image: umutayb/vue-test-website:latest
    build:
      context: .
    restart: always
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge